# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Simpson Lab Webpage
tagline:          'SimpsonLab Webpage'
description:      'Simpson Lab at the Ontario Institute for Cancer Research'
baseurl: ""
url: ""

include:
  - .htaccess
  - _pages

sass:
  sass_dir: _sass

author:
  name:           'Jared Simpson'
  url:            https://twitter.com/jaredtsimpson

paginate:         5

# Custom vars
version:          1.0
markdown:         kramdown

authors:
    jared:
        display_name: Jared Simpson
    jonathan:
        display_name: Jonathan Dursi

github:
  repo:           https://github.com/simpsonlab/simpsonlab.github.io
