# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Simpson Lab Blog
tagline:          'SimpsonLab blog'
description:      'A blog for the Simpson Lab at the Ontario Institute for Cancer Research'
url:              simpsonlab.github.io
baseurl:          /

author:
  name:           'Jared Simpson'
  url:            https://twitter.com/jaredtsimpson

paginate:         5

# Custom vars
version:          1.0
markdown:         kramdown

pages_list:       
  About: '/about'
  Archive: '/archive'

authors:
    jared:
        display_name: Jared Simpson
    jonathan:
        display_name: Jonathan Dursi

github:
  repo:           https://github.com/simpsonlab/simpsonlab.github.io
